---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    k8s-app: flame-controller
  name: flame-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flame-controller
subjects:
  - kind: ServiceAccount
    name: flame-controller
    namespace: flame
