---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    k8s-app: flame-controller
  name: flamepools.flame.org
spec:
  group: flame.org
  names:
    kind: FlamePool
    plural: flamepools
    shortNames:
      - framepool
      - framepools
      - pool
      - pools
    singular: flamepool
  scope: Namespaced
  versions:
    - deprecationWarning:
      name: v1
      schema:
        openAPIV3Schema:
          properties:
            status:
              properties:
                observedGeneration:
                  type: integer
              type: object
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
