---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    k8s-app: flame-controller
  name: flamerunners.flame.org
spec:
  group: flame.org
  names:
    kind: FlameRunner
    plural: flamerunners
    shortNames:
      - fr
      - flamerunner
      - flamerunners
      - runner
      - runners
    singular: flamerunner
  scope: Namespaced
  versions:
    - deprecationWarning:
      name: v1
      schema:
        openAPIV3Schema:
          properties:
            status:
              properties:
                observedGeneration:
                  type: integer
              type: object
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
