---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - flamepool.crd.yaml
  - flamerunner.crd.yaml
  - service.yaml
  - deployment.yaml
  - mutatingwebhookconfiguration.yaml
  - flamepool.yaml
