---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: flame-k8s
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: flame-k8s
        namespace: flame
        path: /admission-review/mutating
        port: 443
    failurePolicy: Ignore
    matchPolicy: Equivalent
    name: flame-k8s.flame.org
    rules:
      - apiGroups:
          - apps
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - deployments
          - statefulsets
