---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: flame-controller
  name: flame-controller
  namespace: flame
spec:
  ports:
    - name: webhooks
      port: 443
      protocol: TCP
      targetPort: webhooks
  selector:
    k8s-app: flame-controller
